substitutions:
  _AR_REGION: us-central1
  _DEPLOY_REGION: us-central1
  _AR_REPO: los-papatos
  _IMAGE: web
  _TAG: $SHORT_SHA
  _SERVICE: los-papatos-web-stg

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_STANDARD_4

steps:
  # Build image
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${_TAG}'
      - '.'

  # Push image
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'push'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${_TAG}'

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${_TAG} \
          --region ${_DEPLOY_REGION} \
          --allow-unauthenticated \
          --platform managed \
          --port 3000 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1

images:
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${_TAG}'